name: "ml_xu_personalized"

feature_definition:
  use_norm_features: False # whether to use normalized features
  empty_feature_filtering_th: 0.5 # remove features based on a threshold
  include_device_type: False # whether to include device type in the feature matrix
  # Feature used in the paper (a subset that is compatible within the dataset)
  feature_list_base: [
            "f_loc:phone_locations_doryab_numberofsignificantplaces",
            "f_loc:phone_locations_doryab_numberlocationtransitions",
            "f_loc:phone_locations_doryab_radiusgyration",
            "f_loc:phone_locations_doryab_timeattop1location",
            "f_loc:phone_locations_doryab_timeattop2location",
            "f_loc:phone_locations_doryab_timeattop3location",
            "f_loc:phone_locations_doryab_movingtostaticratio",
            "f_loc:phone_locations_doryab_outlierstimepercent",
            "f_loc:phone_locations_doryab_avglengthstayatclusters",
            "f_loc:phone_locations_doryab_maxlengthstayatclusters",
            "f_loc:phone_locations_doryab_minlengthstayatclusters",
            "f_loc:phone_locations_doryab_stdlengthstayatclusters",
            "f_loc:phone_locations_doryab_locationentropy",
            "f_loc:phone_locations_doryab_normalizedlocationentropy",
            "f_loc:phone_locations_doryab_timeathome",
            "f_loc:phone_locations_barnett_circdnrtn",
            "f_loc:phone_locations_doryab_loglocationvariance",
            "f_loc:phone_locations_doryab_totaldistance",
            "f_loc:phone_locations_locmap_duration_in_locmap_study",
            "f_loc:phone_locations_locmap_percent_in_locmap_study",
            "f_loc:phone_locations_locmap_duration_in_locmap_exercise",
            "f_loc:phone_locations_locmap_percent_in_locmap_exercise",
            "f_loc:phone_locations_locmap_duration_in_locmap_greens",
            "f_loc:phone_locations_locmap_percent_in_locmap_greens",
            "f_screen:phone_screen_rapids_countepisodeunlock",
            "f_screen:phone_screen_rapids_sumdurationunlock",
            "f_screen:phone_screen_rapids_maxdurationunlock",
            "f_screen:phone_screen_rapids_mindurationunlock",
            "f_screen:phone_screen_rapids_avgdurationunlock",
            "f_screen:phone_screen_rapids_stddurationunlock",
            "f_screen:phone_screen_rapids_firstuseafter00unlock",
            "f_slp:fitbit_sleep_intraday_rapids_countepisodeasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_countepisodeawakeunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_sumdurationawakeunifiedmain", 
            "f_slp:fitbit_sleep_intraday_rapids_avgdurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_avgdurationawakeunifiedmain", 
            "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_mindurationawakeunifiedmain", 
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain", 
            "f_slp:fitbit_sleep_intraday_rapids_ratiocountasleepunifiedwithinmain",
            "f_slp:fitbit_sleep_intraday_rapids_ratiocountawakeunifiedwithinmain",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationawakeunifiedwithinmain",
            "f_steps:fitbit_steps_intraday_rapids_sumsteps",
            "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationsedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_mindurationsedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_avgdurationsedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationactivebout",
            "f_steps:fitbit_steps_intraday_rapids_mindurationactivebout",
            "f_steps:fitbit_steps_intraday_rapids_avgdurationactivebout",
        ]

  feature_list_more_feat_types_base: [
            "f_loc:phone_locations_doryab_numberofsignificantplaces",
            "f_loc:phone_locations_doryab_numberlocationtransitions",
            "f_loc:phone_locations_doryab_radiusgyration",
            "f_loc:phone_locations_doryab_timeattop1location",
            "f_loc:phone_locations_doryab_timeattop2location",
            "f_loc:phone_locations_doryab_timeattop3location",
            "f_loc:phone_locations_doryab_movingtostaticratio",
            "f_loc:phone_locations_doryab_outlierstimepercent",
            "f_loc:phone_locations_doryab_avglengthstayatclusters",
            "f_loc:phone_locations_doryab_maxlengthstayatclusters",
            "f_loc:phone_locations_doryab_minlengthstayatclusters",
            "f_loc:phone_locations_doryab_stdlengthstayatclusters",
            "f_loc:phone_locations_doryab_locationentropy",
            "f_loc:phone_locations_doryab_normalizedlocationentropy",
            "f_loc:phone_locations_doryab_timeathome",
            "f_loc:phone_locations_barnett_circdnrtn",
            "f_loc:phone_locations_doryab_loglocationvariance",
            "f_loc:phone_locations_doryab_totaldistance",
            "f_loc:phone_locations_locmap_duration_in_locmap_study",
            "f_loc:phone_locations_locmap_percent_in_locmap_study",
            "f_loc:phone_locations_locmap_duration_in_locmap_exercise",
            "f_loc:phone_locations_locmap_percent_in_locmap_exercise",
            "f_loc:phone_locations_locmap_duration_in_locmap_greens",
            "f_loc:phone_locations_locmap_percent_in_locmap_greens",
            "f_screen:phone_screen_rapids_countepisodeunlock",
            "f_screen:phone_screen_rapids_sumdurationunlock",
            "f_screen:phone_screen_rapids_maxdurationunlock",
            "f_screen:phone_screen_rapids_mindurationunlock",
            "f_screen:phone_screen_rapids_avgdurationunlock",
            "f_screen:phone_screen_rapids_stddurationunlock",
            "f_screen:phone_screen_rapids_firstuseafter00unlock",
            "f_slp:fitbit_sleep_intraday_rapids_countepisodeasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_countepisodeawakeunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_sumdurationawakeunifiedmain", 
            "f_slp:fitbit_sleep_intraday_rapids_avgdurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_avgdurationawakeunifiedmain", 
            "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_mindurationawakeunifiedmain", 
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain", 
            "f_slp:fitbit_sleep_intraday_rapids_ratiocountasleepunifiedwithinmain",
            "f_slp:fitbit_sleep_intraday_rapids_ratiocountawakeunifiedwithinmain",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationawakeunifiedwithinmain",
            "f_steps:fitbit_steps_intraday_rapids_sumsteps",
            "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationsedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_mindurationsedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_avgdurationsedentarybout",
            "f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationactivebout",
            "f_steps:fitbit_steps_intraday_rapids_mindurationactivebout",
            "f_steps:fitbit_steps_intraday_rapids_avgdurationactivebout",
            "f_blue:phone_bluetooth_doryab_countscansmostfrequentdeviceacrossdatasetothers",
            "f_blue:phone_bluetooth_doryab_countscansmostfrequentdeviceacrossdatasetown",
            "f_blue:phone_bluetooth_doryab_meanscansothers",
            "f_blue:phone_bluetooth_doryab_meanscansown",
            "f_blue:phone_bluetooth_doryab_uniquedevicesothers",
            "f_blue:phone_bluetooth_doryab_uniquedevicesown",
            "f_call:phone_calls_rapids_incoming_count",
            "f_call:phone_calls_rapids_incoming_distinctcontacts",
            "f_call:phone_calls_rapids_incoming_sumduration",
            "f_call:phone_calls_rapids_missed_count",
            "f_call:phone_calls_rapids_outgoing_count",
            "f_call:phone_calls_rapids_outgoing_distinctcontacts",
            "f_call:phone_calls_rapids_outgoing_sumduration",
        ]


training_params:
  verbose: 0
  # whether to save and re-use features repetitively
  #     True only when re-running the exact same model training
  save_and_reload: False
